### PR TITLE
Added originalImage that will persist as the image under the strokes.

### PR DESCRIPTION
**Pull request by gohjohn**
This feature should be a solution to issue #34 

Use setOriginalImage to set an image that will be placed under all strokes.

The image will persist undos and clears and redraws.

To remove the image, call setOriginalImage with a nil param

### CODE REVIEW

**Comment by dehli** [comment]
Thanks for the PR @gohjohn! Since `TouchDrawView` inherits from `UIImageView`,  it already has an `image` property. I think we can probably solve this only using that instead of introducing an other image variable. I'll mess around with getting it working (and if it's not possible I will merge this PR). Cheers! :+1:

**Comment by gohjohn** [comment]
Cheers! 👍

**Comment by dehli** [comment]
Hey @gohjohn, sorry it took so long for me to get to this! I submitted another PR (#38) where I solved the problem a little differently. If you get a chance to look through it/test it out, let me know your thoughts!

**Comment by dehli** [comment]
Closing this PR as it's been implemented slightly differently with https://github.com/dehli/TouchDraw/commit/becd1dc391db1f8df2aa469a04dcddfb61abc144. Let me know if there's any issues with it!

**Pull request closed without merging**
